config/routes.rb
Projects::Application.routes.draw do
  root :to => "companies#index"
  resources :categories do
      collection do
        get :company
      end
  end

  resources :companies do
   resources :partners 
   resources :experiences
	collection do
	get :search
	end

  end
  resources :users
  resources :bids
  resource :session
match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

resources :categories

end

app/models/bid.rb
require 'carrierwave/orm/activerecord'
class Bid < ActiveRecord::Base
  
validates :description, :length => { :within => 10..150 }
validates :buyer, :presence => true
validates :location, :presence => true
validates :sector, :presence => true
validates :description, :presence => true
validates :name, :presence => true
validates :email, :presence => true
validates :attachment, :presence => true
#has_attached_file :attachment
belongs_to :user
mount_uploader :attachment, AttachmentUploader
end

app/controllers/bids_controller.rb
class BidsController < ApplicationController
before_filter :authenticate, :except => [:index, :show]
  # GET /bids
  # GET /bids.json
  def index
  #  @bids = Bid.all
   #@bids = Bid.order("opening_date DESC")
   @bids = Bid.order("opening_date DESC").paginate(page: params[:page], per_page: 10)
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @bids }
    end
  end

  # GET /bids/1
  # GET /bids/1.json
  def show
    @bid = Bid.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/new
  # GET /bids/new.json
  def new
    @bid = Bid.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @bid }
    end
  end

  # GET /bids/1/edit
  def edit
   # @bid = Bid.find(params[:id])
   begin
    @bid = current_user.bids.find(params[:id])
   rescue Exception => e
    render :action => 'error'
   end
  end

  # POST /bids
  # POST /bids.json
  def create
   # @bid = Bid.new(params[:bid])
   @bid = current_user.bids.new(params[:bid])
    uploader = AttachmentUploader.new
    #uploader.store!(my_file)

    respond_to do |format|
      if @bid.save
        format.html { redirect_to @bid, notice: 'Bid was successfully created.' }
        format.json { render json: @bid, status: :created, location: @bid }
      else
        format.html { render action: "new" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /bids/1
  # PUT /bids/1.json
  def update
#    @bid = Bid.find(params[:id])
     @bid = current_user.bids.find([:id])
    respond_to do |format|
      if @bid.update_attributes(params[:bid])
        format.html { redirect_to @bid, notice: 'Bid was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @bid.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /bids/1
  # DELETE /bids/1.json
#  def destroy
#    @bid = Bid.find(params[:id])
 #    @bid = current_user.bids.find(params[:id]) 
  # @bid.destroy

   # respond_to do |format|
    #  format.html { redirect_to bids_url }
     # format.json { head :ok }
   # end
 # end
 
 # truncate(@text, :length => 17)

#Excerpt is nice to know too, it lets you display an excerpt of a text Like so:

 #excerpt('This is an example', 'an', :radius => 5)
 
end

app/helpers/bids_helper.rb
module BidsHelper
end

app/views/bids/_form.html.erb
<%= form_for @bid, :html =>{:multipart =>true} do |f| %>
  <% if @bid.errors.any? %>
    <div id="error_explanation">
      <p class="error"><%= pluralize(@bid.errors.count, "error") %> prohibited this bid from being saved:</p>

      <ul>
      <% @bid.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :buyer %><br />
    <%= f.text_field :buyer %>
  </div>
  <div class="field">
    <%= f.label :location %><br />
    <%= f.text_field :location %>
  </div>
  <div class="field">
    <%= f.label :sector %><br />
    <%= f.text_field :sector %>
  </div>
  <div class="field">
    <%= f.label :description %><br />
    <%= f.text_area :description, rows:7, cols:40 %>
  </div>
  <div class="field">
    <%= f.label :opening_date %><br />
    <%= f.datetime_select :opening_date %>
  </div>
  <div class="field">
    <%= f.label :closing_date %><br />
    <%= f.datetime_select :closing_date %>
  </div>
  <div class="field">
    <%= f.label :name %><br />
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :phone %><br />
    <%= f.number_field :phone %>
  </div>
  <div class="field">
    <%= f.label :addition_info %><br />
    <%= f.text_area :addition_info, rows: 3, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :attachement %><br />
    <%= f.file_field :attachment %>
    <%= f.hidden_field :attachment_cache %>

  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/bids/edit.html.erb
<h1>Editing bid</h1>

<%= render 'form' %>

<%= link_to 'Show', @bid %> |
<%= link_to 'Back', bids_path %>

app/views/bids/error.html.erb
<p id="notice"> permission denied ! </p>

app/views/bids/index.html.erb
<table id="hor-minimalist-b" summary="companies table">
<tr>
   <th scope="col">Buyer</th>
   <th scope="col">Description</th>
    <th scope="col">Location</th>
    <th scope="col">Sector</th>
    <th scope="col">Closing Date</th>
  </tr>
<% @bids.each do |bid| %>
<tbody>
<tr>
    <td><%= link_to bid.buyer, bid %></td>
    <td><%= bid.description %></td>
    <td><%= bid.location %></td>
    <td><%= bid.sector %></td>
    <td><%= bid.closing_date %></td>
  </tr>
<% end %>
</tbody>
</table>

<br />
<%= will_paginate @companies %><br/>
<%= link_to 'New Bid', new_bid_path %>

app/views/bids/new.html.erb
<h2 class="title" >New bid</h2>

<%= render 'form' %>

<%= link_to 'Back', bids_path %>

app/views/bids/show.html.erb
<p id="success"><%= notice %></p>

<table id="box-table-a" summary="companies table">

<tr>
   <th>Buyer</th>
   <th> Location</th>
    <th>Sector</th>
  </tr>
<tr><td><%= @bid.buyer %></td><td><%= @bid.location %></td><td><%= @bid.sector %></td></tr>

<tr>
<th colspan="3">Description of the Product/Services Required</th>
</tr>
<tr><td colspan="3"><%= @bid.description %></td></tr>
<tr><th colspan="3"></th></tr>
<tr><td colspan="2"><b>Opening Date</b>: </td><td><%= @bid.opening_date %></td></tr>
<tr><td colspan="2"><b>Closing Date</b>: </td><td><%= @bid.closing_date %></td></tr>
<tr><th colspan="3">Contact details</th></tr>
<tr><td><%= @bid.name %></td><td><%= @bid.phone %></td><td><%= @bid.email %></td></tr>
<tr><th> Additional Info </th><td colspan="2"></td></tr>
<tr><td colspan="3"><%= @bid.addition_info %></td></tr>
<tr><td colspan="3"><b>Attachment:</b></td></tr>
<tr><td colspan="2"> <%= link_to 'Download attachment..', @bid.attachment.url %> </td>
<td><%= link_to image_tag("download.gif"), @bid.attachment.url %></td>
</tr>
</table>

<%= link_to 'Edit', edit_bid_path(@bid) %> |
<%= link_to 'Back', bids_path %>