config/routes.rb
Projects::Application.routes.draw do
  root :to => "companies#index"
  resources :categories do
      collection do
        get :company
      end
  end

  resources :companies do
   resources :partners 
   resources :experiences
	collection do
	get :search
	end

  end
  resources :users
  resources :bids
  resource :session
match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

resources :categories

end

app/models/company.rb
class Company < ActiveRecord::Base
  validates :org_name, :presence => true
  validates :service_description, :presence => true
  validates :isa_license, :presence => true
  validates :address, :presence => true
  validates :email, :presence => true
  
	belongs_to :user
	#attr_accessible :partners_attributes
	has_many :partners, :dependent => :destroy
	accepts_nested_attributes_for :partners, :allow_destroy => :true
	has_many :experiences, :dependent => :destroy
	accepts_nested_attributes_for :experiences, :allow_destroy => :true
	has_and_belongs_to_many :categories
	simple_search :org_name, :service_description
	scope :reg, where("companies.reg_date IS NOT NULL")
	scope :recent, lambda { reg.where("companies.reg_date > ?",
1.week.ago.to_date)}

end

app/controllers/companies_controller.rb
class CompaniesController < ApplicationController
  before_filter :authenticate, :except => [:index, :show, :search]

def search
@companies = Company.search(params[:keyword])
render :action => 'index'
end


  # GET /companies
  # GET /companies.json
  def index
    #@companies = Company.all
    @companies = Company.order("reg_date DESC").paginate(page: params[:page], per_page: 10)
    #@posts = Post.where(:published => true).page(1).order('created_at DESC')
    

    respond_to do |format|
      format.html # index.html.erb
      #format.js
      format.json { render json: @companies }
    end
  end

  # GET /companies/1
  # GET /companies/1.json
  def show
    @company = Company.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
	format.js
#     format.js {@current_comp = @company}
	 format.json { render json: @company }
    end
  end

  # GET /companies/new
  # GET /companies/new.json
  def new
    @company = Company.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @company }
    end
  end

  # GET /companies/1/edit
  def edit
     if(current_user.role == "admin")
         @company = Company.find(params[:id])
     else
       begin
         @company = current_user.companies.find(params[:id])
         rescue Exception => e
	render :action => 'error'
       end
   end

end

          # POST /companies
  # POST /companies.json
  def create
   if(current_user.role == "admin")
      @company = Company.new(params[:company])
   else
      @company = current_user.companies.new(params[:company])
   end
   @company.reg_date = Time.now
respond_to do |format|
      if @company.save
        format.html { redirect_to @company, notice: 'Company was successfully created.' }
        format.json { render json: @company, status: :created, location: @company }
      else
        format.html { render action: "new" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end
end
  # PUT /companies/1
  # PUT /companies/1.json
  def update
   if(current_user.role == "admin") 
      @company = Company.find(params[:id])
   else
      @company = current_user.companies.find(params[:id]) 
   end
respond_to do |format|
      if @company.update_attributes(params[:company])
        format.html { redirect_to @company, notice: 'Company was successfully updated.' }
        format.json { head :ok }
      else
        format.html { render action: "edit" }
        format.json { render json: @company.errors, status: :unprocessable_entity }
      end
    end

  end

  # DELETE /companies/1
  # DELETE /companies/1.json
  def destroy
  # @company = current_user.companies.find(params[:id])
if(current_user.role == "admin") 
   @company = Company.find(params[:id])
   @company.destroy
else
   flash[:error] = "Permission denied !"
      redirect_to companies_url
end
    respond_to do |format|
      format.html { redirect_to companies_url }
      format.json { head :ok }
    end
  end
end

app/helpers/companies_helper.rb
module CompaniesHelper
end

app/views/companies/_companies.html.erb
<% @companies.each do |company| %>
<tbody>  
<tr>
    <td><%= link_to company.org_name, company %></td>
    <td><%= company.stablished_year %></td>
    <td><%= company.business_size %></td>
    <td><%= company.service_description[0..29] %></td>
<% if logged_in? %>
<% if current_user.role == "admin" %>

<td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
<% end %>
<% end %>  
</tr>
<% end %>
</tbody>
</table>
<%= will_paginate @companies %>

app/views/companies/_form.html.erb
<%= nested_form_for(@company) do |f| %>
  <% if @company.errors.any? %>
    <div id="error_explanation">
      <p class="error"><%= pluralize(@company.errors.count, "error") %> prohibited this company from being saved:</p>

      <ul>
      <% @company.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
  <%= f.label "Company Name *" %><br />
    <%= f.text_field :org_name %>
  </div>
<div class="field">
<%= f.label "Categories" %><br />
<% for category in Category.all %>
<%= check_box_tag 'company[category_ids][]', category.id,
@company.category_ids.include?(category.id), :id => dom_id(category) %>
<%= label_tag dom_id(category), category.name, :class => "check_box_label" %>
<% end %>
</div>


   <div class="field">
    <%= f.label "have ISA license? *" %><br />
    <%= f.text_field :isa_license %>
  </div>
  <div class="field">
    <%= f.label :stablished_year%><br />
    <%= f.date_select :stablished_year %>
  </div>
  <div class="field">
    <%= f.label :business_size %><br />
    <%= f.text_field :business_size %>
  </div>
  <div class="field">
    <%= f.label :service_description %><br />
    <%= f.text_area :service_description, rows: 6, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :address %><br />
    <%= f.text_area :address, rows: 3, cols: 40 %>
  </div>
  <div class="field">
    <%= f.label :email %><br />
    <%= f.text_field :email %>
  </div>
  <div class="field">
    <%= f.label :website %><br />
    <%= f.text_field :website %>
  </div>
  <br/><br/>
  <% if logged_in? %>
<div class="field">
<%= f.fields_for :partners do |partner_form| %>
  <div class="field">
    <%= partner_form.label "Partner's Name" %> <%= partner_form.text_field :name %>
  </div>
  <div class="field">
	  <%= partner_form.label "Partner's Info" %> <%= partner_form.text_area :info, rows:2, cols:30 %>
  </div>
  <%= partner_form.link_to_remove "Remove this partner" %>
<% end %>
<br/><br/>
<p><%= f.link_to_add "Add a partner", :partners %></p>
</div>

<div class="field">
<%= f.fields_for :experiences do |experience_form| %>
   <div class="field">
    <%= experience_form.label :customer %> <%= experience_form.text_field :customer %>
  </div>
  <div class="field">
    <%= experience_form.label :location %> <%= experience_form.text_field :location %>
  </div>
  <div class="field">
    <%= experience_form.label :date %> <%= experience_form.date_select :date %>
  </div>
  <div class="field">
    <%= experience_form.label :duration %> <%= experience_form.text_field :duration %>
  </div>
  <div class="field">
    <%= experience_form.label :project_cost %> <%= experience_form.text_field :project_cost %>
  </div>
  <div class="field">
    <%= experience_form.label :project_description %> <%= experience_form.text_area :project_description %>
  </div>
  <%= experience_form.link_to_remove "Remove this experience" %>
<% end %>
<br/><br/>
<p><%= f.link_to_add "Add an experience", :experiences %></p>
</div>

<% end %>
 <div class="actions">
	<%= f.submit %>
  </div>
<% end %>

app/views/companies/_recent.html.erb
<% for @company in Company.recent %>
    <li><%= link_to @company.org_name, @company %></li>
<% end %>

app/views/companies/_search.html.erb
<%= form_tag search_companies_path, :method => :get do %>
<p>
Search
<%= text_field_tag :keyword, params[:keyword] %>
</p>
<% end %>

app/views/companies/edit.html.erb
<%= render 'form' %>

<%= link_to 'Show', @company %> |
<%= link_to 'Back', companies_path %>

app/views/companies/error.html.erb
<p id="notice"> permission denied ! </p>

app/views/companies/index.html.erb
<%= content_tag(:p, notice, :class => 'success') if notice.present? %>
<table id="hor-minimalist-b" summary="companies table">
<tr>
   <th scope="col">Company</th>
    <th scope="col">Stablished.Y</th>
    <th scope="col">Busines Size</th>
    <th scope="col">Service Desription</th>
  </tr>
  <%= render partial: 'companies' %>

<br />
<%= link_to 'New Company', new_company_path %>

app/views/companies/index.js.erb
$('#companies').html('<%= render partial: 'companies' %>');
$.setAjaxPagination();

app/views/companies/index_default.html.erb
<h1>Listing companies</h1>
<table id="hor-minimalist-a" summary="Employee Pay Sheet">
<thead>  
<tr>
    <th>Org name</th>
    <th>Isa license</th>
    <th>Stablished year</th>
    <th>Business size</th>
    <th>Service description</th>
    <th>Address</th>
    <th>Email</th>
    <th>Website</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>
</thead>
<% @companies.each do |company| %>
<tbody>  
<tr>
    <td><%= company.org_name %></td>
    <td><%= company.isa_license %></td>
    <td><%= company.stablished_year %></td>
    <td><%= company.business_size %></td>
    <td><%= company.service_description %></td>
    <td><%= company.address %></td>
    <td><%= company.email %></td>
    <td><%= company.website %></td>
    <td><%= link_to 'Show', company %></td>
    <td><%= link_to 'Edit', edit_company_path(company) %></td>
    <td><%= link_to 'Destroy', company, confirm: 'Are you sure?', method: :delete %></td>
  </tr>
<% end %>
</tbody>
</table>
<br />

<%= link_to 'New Company', new_company_path %>

app/views/companies/new.html.erb
<%= render 'form' %>
<%= link_to 'Back', companies_path %>

app/views/companies/show.html.erb
<p id="success"><%= notice %></p>

<table id="box-table-a" summary="companies table">
<thead>
<tr>
   <th scope="col">Company</th>
   <th scope="col"> IsaLicense</th>
    <th scope="col">StablishedYr</th>
    <th scope="col">BusSize</th>
  </tr>
<tr>
</thead>
    <td><%= @company.org_name %></td>
    <td> <%= @company.isa_license %></td>
    <td><%= @company.stablished_year %></td>
    <td><%= @company.business_size %></td>
  </tr>
<tr>
    <th>Service Description</th>
<td colspan="3"><%= @company.service_description %></td>
</tr>
<tr>
<th>company website</th><th>Address</th>
<th></th><th></th>
</tr>
<tr>
<td><%= link_to @company.website, @company %></td>
<td colspan="3"><%= @company.address %></td>
</tr>
<tr>
<th>Experiences</th><th></th><th></th><th></th>
</tr>
<tr>
<td colspan="4"><%= render @company.experiences %>
</tr>
<tr>
<th>Partners</th><th></th><th></th><th>Company's Email</th>
</tr>
<tr>
<td colspan="3"><%= render @company.partners %></td>
<td><%= @company.email %></td> 
</tr>
</table>
<br/><br/>
<%= link_to 'Edit', edit_company_path(@company) %> |
<%= link_to 'Back', companies_path %>