config/routes.rb
Projects::Application.routes.draw do
  root :to => "companies#index"
  resources :categories do
      collection do
        get :company
      end
  end

  resources :companies do
   resources :partners 
   resources :experiences
	collection do
	get :search
	end

  end
  resources :users
  resources :bids
  resource :session
match '/login' => "sessions#new", :as => "login"
match '/logout' => "sessions#destroy", :as => "logout"

resources :categories

end

app/views/layouts/application.html.erb
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"><html xmlns="http://www.w3.org/1999/xhtml" dir="ltr" lang="en-US">

<head profile="http://gmpg.org/xfn/11">
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" />

<title>Project.Af</title>
 	<%= stylesheet_link_tag "application" %>
	<%= stylesheet_link_tag "screen" %>
 	<%= javascript_include_tag "application" %>
 	<%= csrf_meta_tag %>

<title> Projects.Af</title>
<link rel="stylesheet" href="http://localhost/blog/wp-content/themes/Perfecta/css/print.css" type="text/css" media="print" />
<!--[if IE]><link rel="stylesheet" href="http://localhost/blog/wp-content/themes/Perfecta/css/ie.css" type="text/css" media="screen, projection"><![endif]-->
<link rel="stylesheet" href="http://localhost/blog/wp-content/themes/Perfecta/style.css" type="text/css" media="screen" />
<link rel="stylesheet" href="http://localhost/blog/wp-content/themes/Perfecta/jdgallery/jd.gallery.css" type="text/css" media="screen" charset="utf-8" />
<script src="http://localhost/blog/wp-content/themes/Perfecta/jdgallery/mootools-1.2.5-core-yc.js" type="text/javascript"></script>
<script src="http://localhost/blog/wp-content/themes/Perfecta/jdgallery/mootools-1.2-more.js" type="text/javascript"></script>
<script src="http://localhost/blog/wp-content/themes/Perfecta/jdgallery/jd.gallery.js" type="text/javascript"></script>

<script src="http://localhost/blog/wp-content/themes/Perfecta/jdgallery/jd.gallery.transitions.js" type="text/javascript"></script>
<!--[if IE 6]>
	<script src="http://localhost/blog/wp-content/themes/Perfecta/js/pngfix.js"></script>
<![endif]--> 
<link rel="alternate" type="application/rss+xml" title="dandeh RSS Feed" href="http://localhost/blog/?feed=rss2" />
<link rel="alternate" type="application/atom+xml" title="dandeh Atom Feed" href="http://localhost/blog/?feed=atom" />
<link rel="pingback" href="http://localhost/blog/xmlrpc.php" />

<link rel='stylesheet' id='admin-bar-css'  href='http://localhost/blog/wp-includes/css/admin-bar.css?ver=20110622' type='text/css' media='all' />
<script type='text/javascript' src='http://localhost/blog/wp-includes/js/l10n.js?ver=20101110'></script>
<link rel="EditURI" type="application/rsd+xml" title="RSD" href="http://localhost/blog/xmlrpc.php?rsd" />
<link rel="wlwmanifest" type="application/wlwmanifest+xml" href="http://localhost/blog/wp-includes/wlwmanifest.xml" /> 
<link rel='index' title='dandeh' href='http://localhost/blog' />
<meta name="generator" content="WordPress 3.2.1" />
<style type="text/css" media="print">#wpadminbar { display:none; }</style>
<style type="text/css" media="screen">
	html { margin-top: 28px !important; }
	* html body { margin-top: 28px !important; }

</style>
</head>
<body>
	<div id="wrapper">
	<div id="container" class="container">  
			
        	<div class="span-3">
                	<div class="topleft">
				<a href="#"><%= image_tag("rss.png") %></a>		
					&nbsp; <a href="#" title="Follow me!"><%= image_tag("twitter.png") %></a>
				</div>
            </div><!-- end div span-3-->

            
            <div class="span-21 last">
		<div id="pagemenucontainer">
		   <ul id="pagemenu">
			<li  class="current_page_item" ><a href="http://projects.af">Home</a></li>
				<li  class="page_item page-item-2" ><a href="http://projects.af/companies/new">Register Your Company</a></li>
			<li class="page_item page-item-2"><a href="#" title="Sample Page">About us</a></li>
			<li class="page_item page-item-2">
						<% if logged_in? %>
						<%= link_to "Logout", logout_path %>
						<% else %>
						<%= link_to "Login / Register", login_path %>
						<% end %></li>
		   </ul>
		</div>
            </div>
            
            
	<div id="header" class="span-24">

	  <div class="span-12">
		<a href="http://projects.af"><%= image_tag("logo.png") %></a>
													
	 </div>
					
	</div>
			
	<div class="span-24">
	  <div class="navcontainer">

            <ul id="nav">
		<li  class="current-cat" ><a href="http://projects.af">Home</a></li>
		<li class="cat-item cat-item-1"><%= link_to "Bids", bids_path %></li>
		<li class="cat-item cat-item-1"><%= link_to "Companies", companies_path %></li>	
	    </ul>
                        					
	  </div>
        </div>	


<!-- header end -->
<div class="span-24" id="contentwrap">
            <div class="span-5">

		<div class="sidebar sidebar-left">
		
			<ul>
					
					
                    
				<li class="categories"><h2>Categories</h2><ul>
		
				<%= render 'categories/all' %></ul>
	
	
	</li>				
					
					
					
									<li><h2>Recent Companies</h2>
<ul>
<%= render 'companies/recent' %>
	
</ul></li>	
<li><h2>Advertise here</h2>
				               <ul>
							
				               </ul>
					</li>			
						
					
					
							</ul>
			
				<div class="sidebaradbox">
			<a href="#"><%= image_tag("fth.gif") %> </a>		</div>
				</div>

</div>			<div class="span-14">
				<div id="content">		
                								
	<div class="post-1 post type-post status-publish format-standard hentry category-uncategorized" id="post-1">
		<div class="postdate"><%= image_tag("date.png") %> <%= Time.now %><%= image_tag("user.png") %><% if logged_in? %> Hi <%= current_user.name %> <% end %> </div>
			
			<div class="entry">
				<div id="main">			
				  <%= yield %>
				</div>
			</div>
	</div><!--/post-1-->
				
								<div class="navigation">

										<div class="alignleft"></div>
					<div class="alignright"></div>
									</div>
								</div>
			</div>
		
		
	<div class="span-5 last">
		<div class="sidebar sidebar-right">
        <div id="topsearch" > 
    		 
<div id="search">

   

<%= form_tag search_companies_path, :method => :get do %>
       
<input type="text" value="Search Company" 
            name="keyword" id="s"  onblur="if (this.value == '')  {this.value = 'Search Company';}"  
            onfocus="if (this.value == 'Search Company') {this.value = '';}" />
        <input type="image" src="http://localhost/blog/wp-content/themes/Perfecta/images/search.gif" style="border:0; vertical-align: top;" /> 
    <% end %>
</div> 
    	</div>
			<ul>

									
					<li id="tag_cloud"><h2>Tags</h2>
                        <div></div>
						
					</li>
					
					<li><h2>Links</h2>
						<ul>
							
						</ul>

					</li>
					
					<li> 
						<h2>Facebook fans</h2>

						
					</li>

					<li id="linkcat-2" class="linkcat"><h2>Contact Us</h2>
	<ul class='xoxo blogroll'>
<li><a href="#">info at projects.af</a></li>


	</ul>
</li>
						
				<li><h2>Meta</h2>
					<ul>
<% if logged_in? %>
<li><%= link_to "Edit Password", edit_user_path(current_user) %> </li>
<li><%= link_to "Logout", logout_path %></li>
<% else %>
<li><%= link_to "Login", login_path %></li>
<% end %>

											</ul>
					</li>
	
							</ul>
				<div class="sidebaradbox">
			<a href="#"> </a>		</div>

				</div>
		
	</div>
	</div>
	<div class="span-24">
    	<div id="footer">Copyright &copy; <a href="projects.af"><strong>projects.af</strong></a>  - ask us about tenders</div>
                <div class="footer_2"> | <a href="#"></a></div>
	</div>
</div>
</div>
</body>
</html>